version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.1
      - image: circleci/postgres:9.6-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    working_directory: /go/src/github.com/lifesum/configsum
    steps:
      - checkout
      - run: env
      - run:
          name: Check dependencies
          environment:
            GOBIN: /go/bin
          command: make check-dependencies
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Run tests
          command: |
            go test -v -race ./pkg/auth/...
            go test -v -race ./pkg/client/... -postgres.uri="postgres://root@127.0.0.1:5432/circle_test?sslmode=disable"
            go test -v -race ./pkg/config/... -postgres.uri="postgres://root@127.0.0.1:5432/circle_test?sslmode=disable"
